In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

데이터 입출력

In [2]:
iris = sns.load_dataset('iris') #data load
X = iris.iloc[:, :4]
y = iris.iloc[:, -1]

scal = StandardScaler() #scaling
X = scal.fit_transform(X)

데이터 셋 분리

In [3]:
svm_1 = SVC(kernel ='rbf', gamma = 5, C = 100)
svm_2 = SVC(kernel ='rbf', gamma = 5, C = 100)
svm_3 = SVC(kernel ='rbf', gamma = 5, C = 100)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=48)
y_train = pd.get_dummies(y_train) #one hot encoding

svm_1.fit(X_train, y_train.iloc[:, 0]) # setosa
svm_2.fit(X_train, y_train.iloc[:, 1]) # versicolor
svm_3.fit(X_train, y_train.iloc[:, 2]) # virginica

SVC(C=100, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=5, kernel='rbf', max_iter=-1,
    probability=False, random_state=None, shrinking=True, tol=0.001,
    verbose=False)

decision_function 값 확인

In [4]:
print(svm_1.decision_function(X_test))
print(svm_2.decision_function(X_test))
print(svm_3.decision_function(X_test))

[-1.12470845 -0.86326953 -0.65281099 -0.50248821 -0.76284323 -0.87465573
  1.07709345 -0.99281647  0.47441336 -0.99842743 -0.83989348  0.15633457
  0.32871788 -0.97965464 -0.72385083 -0.92638376  1.28322481 -0.56240455
 -0.72719892 -0.99509775  0.43166724 -0.96451557 -0.82991366 -1.03020581
 -0.75166835  1.13461335  0.39943974 -1.04194106 -0.93376548 -1.06133798]
[ 1.36054602  0.62859488  0.0580828  -0.36987093 -0.25686625 -0.79229874
 -1.03195247 -0.87132049 -0.77957234  0.99327762 -0.73309581 -0.64607768
 -0.71843897 -0.80882458  0.47748663  0.69953462 -1.11879121 -0.1870504
 -0.24458236 -0.99337352 -0.76149141 -0.96812018  0.11310267  1.06892719
 -0.56749692 -1.05639624 -0.74817515 -1.0537858  -0.89721836  1.17126024]
[-1.26277651 -0.77964936 -0.40539105 -0.13070947  0.02643314  0.57365649
 -1.04443118  0.88027844 -0.69605517 -0.99074328  0.52442024 -0.51171892
 -0.61157919  0.78148257 -0.75517707 -0.76905925 -1.16380018 -0.25333938
 -0.0251979   0.98843144 -0.67129528  0.89577306 -

predict 값 확인

In [5]:
print(svm_1.predict(X_test))
print(svm_2.predict(X_test))
print(svm_3.predict(X_test))

[0 0 0 0 0 0 1 0 1 0 0 1 1 0 0 0 1 0 0 0 1 0 0 0 0 1 1 0 0 0]
[1 1 1 0 0 0 0 0 0 1 0 0 0 0 1 1 0 0 0 0 0 0 1 1 0 0 0 0 0 1]
[0 0 0 0 1 1 0 1 0 0 1 0 0 1 0 0 0 0 0 1 0 1 0 0 1 0 0 1 1 0]


In [6]:
result = []
for i in range(len(X_test)):
    if (svm_1.decision_function(X_test)[i] >= svm_2.decision_function(X_test)[i]) \
            and (svm_1.decision_function(X_test)[i] >= svm_3.decision_function(X_test)[i]):
        result.append(1) # setosa
    elif (svm_2.decision_function(X_test)[i] >= svm_1.decision_function(X_test)[i]) \
            and (svm_2.decision_function(X_test)[i] >= svm_3.decision_function(X_test)[i]):
        result.append(2) # versicolor
    else:
        result.append(3) # virginica
print(result)

[2, 2, 2, 3, 3, 3, 1, 3, 1, 2, 3, 1, 1, 3, 2, 2, 1, 2, 3, 3, 1, 3, 2, 2, 3, 1, 1, 3, 3, 2]


descision_function의 크기로 분류하였습니다. 그런데 시각화나 제가 한게 틀린거 같아서 코멘트 주시면 바로 다시 해보겠습니다.